"""Generate M3 report tables and figures from committed result artifacts."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[3]
REPORT_DIR = ROOT / "reports" / "midterm_review"
FIGURE_DIR = REPORT_DIR / "figures"
INCLUDE_DIR = REPORT_DIR / "include"

RUNS = {
    "ImageNet": ROOT / "results" / "metrics" / "m3_imagenet_default_20260913",
    "CHNCXR": ROOT / "results" / "metrics" / "m3_chncxr_default_20260913",
}
MODELS = ("resnet50", "vgg13")
METHODS = ("ablation", "lime", "rise", "kernel_shap")
RANDOM_METHODS = ("lime", "rise", "kernel_shap")
METHOD_LABELS = {
    "ablation": "Ablation",
    "lime": "LIME",
    "rise": "RISE",
    "kernel_shap": "KernelSHAP",
}
MODEL_LABELS = {"resnet50": "ResNet-50", "vgg13": "VGG13"}
COLORS = {
    "ablation": "#4C78A8",
    "lime": "#F58518",
    "rise": "#54A24B",
    "kernel_shap": "#B279A2",
}


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def read_rows(path: Path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def seed_summary(rows):
    """Match scripts/summarize_m3_run.py: mean pairs per image, median images."""
    output = {}
    for model in MODELS:
        for method in RANDOM_METHODS:
            group = [row for row in rows if row["model"] == model and row["method"] == method]
            record = {}
            for key in ("spearman", "top20_jaccard"):
                per_image = []
                for sample_id in sorted({row["id"] for row in group}):
                    values = [
                        row[key]
                        for row in group
                        if row["id"] == sample_id and row[key] is not None
                    ]
                    per_image.append(float(np.mean(values)))
                record[key] = float(np.median(per_image))
            output[(model, method)] = record
    return output


def bold_if(value: float, best: float | None, digits: int = 4) -> str:
    text = f"{value:.{digits}f}"
    return rf"\textbf{{{text}}}" if best is not None and np.isclose(value, best) else text


def write_table_assets(data):
    lines = [
        "% Generated by scripts/generate_report_assets.py; do not edit by hand.",
        "",
    ]

    # Completeness and accounting audit.
    lines.extend(
        [
            r"\begin{table}[H]",
            r"    \centering",
            r"    \caption{M3 默认设置结果完整性与前向样本审计}",
            r"    \label{tab:m3-audit}",
            r"    \footnotesize",
            r"    \setlength{\tabcolsep}{4pt}",
            r"    \renewcommand{\arraystretch}{0.92}",
            r"    \begin{tabular}{lrrrrr}",
            r"        \toprule",
            r"        数据域 & 完成记录 & 基础归因 & 稳定性重算 & 曲线评价 & 类别变化 \\",
            r"        \midrule",
        ]
    )
    for domain in RUNS:
        audit = data[domain]["audit"]
        lines.append(
            f"        {domain} & {audit['rows']}/{audit['expected']} & "
            f"{audit['base']:,} & {audit['stability']:,} & {audit['evaluation']:,} & "
            f"{audit['prediction_changes']} \\\\"
        )
    lines.extend([r"        \bottomrule", r"    \end{tabular}", r"\end{table}", ""])

    # Fidelity and localization, split by domain to keep the page readable.
    for domain in RUNS:
        lines.extend(
            [
                r"\begin{table}[H]",
                r"    \centering",
                rf"    \caption{{{domain} 默认设置下的忠实性与定位性中位数}}",
                rf"    \label{{tab:{domain.lower()}-fidelity}}",
                r"    \footnotesize",
                r"    \setlength{\tabcolsep}{4pt}",
                r"    \renewcommand{\arraystretch}{0.92}",
                r"    \begin{tabular}{llrrrr}",
                r"        \toprule",
                r"        模型 & 方法 & Insertion$\uparrow$ & Deletion$\downarrow$ & 正能量占比$\uparrow$ & Pointing$\uparrow$ \\",
                r"        \midrule",
            ]
        )
        summary = data[domain]["summary"]
        for model_index, model in enumerate(MODELS):
            group = [summary[(model, method)] for method in METHODS]
            best = {
                "insertion_auc": max(row["insertion_auc"]["median"] for row in group),
                "deletion_auc": min(row["deletion_auc"]["median"] for row in group),
                "localization_energy": max(row["localization_energy"]["median"] for row in group),
                "pointing_game": (
                    max(row["pointing_game"]["median"] for row in group)
                    if len({row["pointing_game"]["median"] for row in group}) > 1
                    else None
                ),
            }
            for method in METHODS:
                row = summary[(model, method)]
                values = [
                    bold_if(row[key]["median"], best[key])
                    for key in (
                        "insertion_auc",
                        "deletion_auc",
                        "localization_energy",
                        "pointing_game",
                    )
                ]
                lines.append(
                    f"        {MODEL_LABELS[model]} & {METHOD_LABELS[method]} & "
                    + " & ".join(values)
                    + r" \\"
                )
            if model_index == 0:
                lines.append(r"        \addlinespace[2pt]")
        lines.extend([r"        \bottomrule", r"    \end{tabular}", r"\end{table}", ""])

    # Input stability for all four methods.
    lines.extend(
        [
            r"{\footnotesize",
            r"\setlength{\tabcolsep}{4pt}",
            r"\renewcommand{\arraystretch}{0.86}",
            r"\begin{longtable}{lllrr}",
            r"    \caption{输入轻微扰动稳定性中位数}\label{tab:input-stability} \\",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & Max-Sensitivity$\downarrow$ & Cosine Similarity$\uparrow$ \\",
            r"        \midrule",
            r"        \endfirsthead",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & Max-Sensitivity$\downarrow$ & Cosine Similarity$\uparrow$ \\",
            r"        \midrule",
            r"        \endhead",
            r"        \midrule",
            r"        \multicolumn{5}{r}{续下页} \\",
            r"        \endfoot",
            r"        \bottomrule",
            r"        \endlastfoot",
        ]
    )
    for domain_index, domain in enumerate(RUNS):
        summary = data[domain]["summary"]
        for model_index, model in enumerate(MODELS):
            group = [summary[(model, method)] for method in METHODS]
            best_sens = min(row["max_sensitivity"]["median"] for row in group)
            best_cos = max(row["cosine_similarity"]["median"] for row in group)
            for method in METHODS:
                row = summary[(model, method)]
                lines.append(
                    f"        {domain} & {MODEL_LABELS[model]} & {METHOD_LABELS[method]} & "
                    f"{bold_if(row['max_sensitivity']['median'], best_sens)} & "
                    f"{bold_if(row['cosine_similarity']['median'], best_cos)} \\\\"
                )
            if not (domain_index == len(RUNS) - 1 and model_index == len(MODELS) - 1):
                lines.append(r"        \addlinespace[2pt]")
    lines.extend([r"\end{longtable}", r"}", ""])

    # Cross-seed stability.
    lines.extend(
        [
            r"{\footnotesize",
            r"\setlength{\tabcolsep}{4pt}",
            r"\renewcommand{\arraystretch}{0.86}",
            r"\begin{longtable}{lllrr}",
            r"    \caption{随机方法的跨种子稳定性中位数}\label{tab:seed-stability} \\",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & Spearman$\uparrow$ & Top 20\% Jaccard$\uparrow$ \\",
            r"        \midrule",
            r"        \endfirsthead",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & Spearman$\uparrow$ & Top 20\% Jaccard$\uparrow$ \\",
            r"        \midrule",
            r"        \endhead",
            r"        \midrule",
            r"        \multicolumn{5}{r}{续下页} \\",
            r"        \endfoot",
            r"        \bottomrule",
            r"        \endlastfoot",
        ]
    )
    for domain_index, domain in enumerate(RUNS):
        seed = data[domain]["seed"]
        for model_index, model in enumerate(MODELS):
            group = [seed[(model, method)] for method in RANDOM_METHODS]
            best_spear = max(row["spearman"] for row in group)
            best_jacc = max(row["top20_jaccard"] for row in group)
            for method in RANDOM_METHODS:
                row = seed[(model, method)]
                lines.append(
                    f"        {domain} & {MODEL_LABELS[model]} & {METHOD_LABELS[method]} & "
                    f"{bold_if(row['spearman'], best_spear)} & "
                    f"{bold_if(row['top20_jaccard'], best_jacc)} \\\\"
                )
            if not (domain_index == len(RUNS) - 1 and model_index == len(MODELS) - 1):
                lines.append(r"        \addlinespace[2pt]")
    lines.extend([r"\end{longtable}", r"}", ""])

    # Efficiency and relative wall-clock ratio.
    lines.extend(
        [
            r"{\footnotesize",
            r"\setlength{\tabcolsep}{4pt}",
            r"\renewcommand{\arraystretch}{0.90}",
            r"\begin{longtable}{lllrrr}",
            r"    \caption{归因阶段效率中位数及相对 Ablation 耗时}\label{tab:efficiency} \\",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & 秒/图$\downarrow$ & 前向数$\downarrow$ & 耗时倍数 \\",
            r"        \midrule",
            r"        \endfirsthead",
            r"        \toprule",
            r"        数据域 & 模型 & 方法 & 秒/图$\downarrow$ & 前向数$\downarrow$ & 耗时倍数 \\",
            r"        \midrule",
            r"        \endhead",
            r"        \midrule",
            r"        \multicolumn{6}{r}{续下页} \\",
            r"        \endfoot",
            r"        \bottomrule",
            r"        \endlastfoot",
        ]
    )
    for domain_index, domain in enumerate(RUNS):
        summary = data[domain]["summary"]
        for model_index, model in enumerate(MODELS):
            baseline = summary[(model, "ablation")]["attribution_seconds"]["median"]
            group = [summary[(model, method)] for method in METHODS]
            best_time = min(row["attribution_seconds"]["median"] for row in group)
            best_forward = min(row["forward_samples"]["median"] for row in group)
            for method in METHODS:
                row = summary[(model, method)]
                seconds = row["attribution_seconds"]["median"]
                forwards = row["forward_samples"]["median"]
                lines.append(
                    f"        {domain} & {MODEL_LABELS[model]} & {METHOD_LABELS[method]} & "
                    f"{bold_if(seconds, best_time)} & {bold_if(forwards, best_forward, 1)} & "
                    rf"{seconds / baseline:.1f}$\times$ \\"
                )
            if not (domain_index == len(RUNS) - 1 and model_index == len(MODELS) - 1):
                lines.append(r"        \addlinespace[2pt]")
    lines.extend([r"\end{longtable}", r"}", ""])

    text = "\n".join(lines)
    blocks = text.split("\n\n")
    header = blocks[0] + "\n\n"
    generated_parts = {
        "generated_audit.tex": blocks[1:2],
        "generated_fidelity.tex": blocks[2:4],
        "generated_stability.tex": blocks[4:6],
        "generated_efficiency.tex": blocks[6:7],
    }
    for name, selected in generated_parts.items():
        (INCLUDE_DIR / name).write_text(header + "\n\n".join(selected) + "\n", encoding="utf-8")


def plot_fidelity(data):
    fig, axes = plt.subplots(2, 2, figsize=(11.2, 4.8))
    x = np.arange(len(METHODS))
    width = 0.36
    for row_index, domain in enumerate(RUNS):
        summary = data[domain]["summary"]
        for column_index, model in enumerate(MODELS):
            ax = axes[row_index, column_index]
            insertion = [summary[(model, method)]["insertion_auc"]["median"] for method in METHODS]
            deletion = [summary[(model, method)]["deletion_auc"]["median"] for method in METHODS]
            ax.bar(x - width / 2, insertion, width, label="Insertion (higher)", color="#4C78A8")
            ax.bar(x + width / 2, deletion, width, label="Deletion (lower)", color="#E45756")
            ax.axhline(0, color="#555555", linewidth=0.8)
            ax.set_xticks(x, [METHOD_LABELS[method] for method in METHODS], rotation=18)
            ax.set_title(f"{domain} / {MODEL_LABELS[model]}")
            ax.set_ylabel("Raw target-logit AUC")
            ax.grid(axis="y", alpha=0.25)
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.suptitle("Default-setting fidelity", fontsize=14, fontweight="bold", y=0.985)
    fig.legend(
        handles,
        labels,
        frameon=False,
        ncol=2,
        loc="upper center",
        bbox_to_anchor=(0.5, 0.955),
    )
    fig.tight_layout(rect=(0, 0, 1, 0.91))
    fig.savefig(FIGURE_DIR / "m3_fidelity_comparison.png", dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_stability_cost(data):
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 4.4), constrained_layout=True)
    markers = {"resnet50": "o", "vgg13": "s"}
    for ax, domain in zip(axes, RUNS):
        summary = data[domain]["summary"]
        seed = data[domain]["seed"]
        for model in MODELS:
            for method in RANDOM_METHODS:
                seconds = summary[(model, method)]["attribution_seconds"]["median"]
                spearman = seed[(model, method)]["spearman"]
                ax.scatter(
                    seconds,
                    spearman,
                    s=85,
                    marker=markers[model],
                    color=COLORS[method],
                    edgecolor="white",
                    linewidth=0.8,
                    zorder=3,
                )
                ax.annotate(
                    METHOD_LABELS[method],
                    (seconds, spearman),
                    xytext=(5, 4 if model == "resnet50" else -11),
                    textcoords="offset points",
                    fontsize=8,
                )
        ax.set_title(domain)
        ax.set_xlabel("Median attribution time (s/image, lower is better)")
        ax.set_ylabel("Median cross-seed Spearman (higher is better)")
        ax.set_ylim(0.25, 1.035)
        ax.grid(alpha=0.25)
    method_handles = [
        plt.Line2D([0], [0], marker="o", linestyle="", color=COLORS[m], label=METHOD_LABELS[m], markersize=7)
        for m in RANDOM_METHODS
    ]
    model_handles = [
        plt.Line2D([0], [0], marker=markers[m], linestyle="", color="#666666", label=MODEL_LABELS[m], markersize=7)
        for m in MODELS
    ]
    axes[0].legend(handles=method_handles + model_handles, frameon=False, ncol=2, loc="lower right")
    fig.suptitle("Cross-seed stability vs. attribution time", fontsize=14, fontweight="bold")
    fig.savefig(FIGURE_DIR / "m3_stability_cost.png", dpi=300)
    plt.close(fig)


def load_data():
    data = {}
    for domain, run_dir in RUNS.items():
        raw_summary = read_json(run_dir / "summary.json")
        summary = {(row["model"], row["method"]): row for row in raw_summary}
        seed_rows = read_json(run_dir / "seed_stability.json")
        rows = read_rows(run_dir / "metrics.jsonl")
        complete = read_json(run_dir / "complete.json")
        audit = {
            "rows": complete["rows"],
            "expected": complete["expected"],
            "base": sum(row["forward_samples"] for row in rows),
            "stability": sum(row["stability_forward_samples"] for row in rows),
            "evaluation": sum(row["evaluation_forward_samples"] for row in rows),
            "prediction_changes": sum(row["prediction_changes"] for row in rows),
        }
        data[domain] = {
            "summary": summary,
            "seed": seed_summary(seed_rows),
            "rows": rows,
            "audit": audit,
        }
    return data


def validate_data(data):
    assert sum(data[d]["audit"]["rows"] for d in RUNS) == 640
    kernel_rows = [
        row
        for domain in RUNS
        for row in data[domain]["rows"]
        if row["method"] == "kernel_shap"
    ]
    assert len(kernel_rows) == 200
    assert all(row["diagnostics"]["design_rank"] == row["actual_regions"] for row in kernel_rows)
    assert max(abs(row["diagnostics"]["efficiency_residual"]) for row in kernel_rows) <= 2.23e-16
    assert all(row["max_sensitivity"] is not None for domain in RUNS for row in data[domain]["rows"])
    assert all(row["cosine_similarity"] is not None for domain in RUNS for row in data[domain]["rows"])
    chncxr_localization = [row for row in data["CHNCXR"]["rows"] if row["localization_eligible"]]
    assert len(chncxr_localization) == 160
    assert sum(row["pointing_game"] for row in chncxr_localization) == 0


def main():
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    data = load_data()
    validate_data(data)
    write_table_assets(data)
    plot_fidelity(data)
    plot_stability_cost(data)
    print(INCLUDE_DIR / "generated_audit.tex")
    print(FIGURE_DIR / "m3_fidelity_comparison.png")
    print(FIGURE_DIR / "m3_stability_cost.png")


if __name__ == "__main__":
    main()
